number1=input('enter number1')
number2=input('enter number2')
number3=input('enter number3')
number4=input('enter number4')
number5=input('enter number5')
sum= int(number1)+int(number2)
print(sum)
multiply=int(number1)*int(number2)*int(number3)
print(multiply)
difference=int(number1)-int(number2)-int(number3)
print(difference)
division=int(number1)/int(number2)/int(number3)
print(division)
print(sum)
print(difference)