input1=5
input2=6
output=input1+input2
print(input1,input2,output)
firstinput=5
secondinput=6
thirdinput=7
output=firstinput*secondinput*thirdinput
print(output)
firstinput=5
secondinput=6
thirdinput=7
fourthinput=8
output1=(firstinput+secondinput+thirdinput+fourthinput)
output2=(firstinput*secondinput*thirdinput*fourthinput)
print(output1,output2)
output=(first input*fourthinput+thirdinput-secondinput)
input1=3
input2=87
input3=10
output=input1+input2+input3
print(output)