number1=input('Enter number 1: ')
number2=input('Enter number 2')
number3=input('enter number3')
print(number1,number2,number3)
print(sum)
difference=int(number1)-int(number2)
print(difference)
multiply=int(number1)*int(number2)
print(multiply)
division=int(number1)/int(number2)
print(division)
print(sum,difference,multiply,division)
sum= int(number1)+int(number2)+int(number3)
print(sum)
difference=int(number1)-int(number2)-int(number3)
print(difference)
division=int(number1)/int(number2)/int(number3)
print(division)
multiply=int(number1)*int(number2)*int(number3)
print(multiply)
print(math.pow)
